apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: nicopaez/password-api:1.5.0-java
    readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          tcpSocket:
            host:
            port: 8080
            path: /actuator/health
    livenessProbe:
      tcpSocket:
            host:
            port: 8080
            path: /actuator/health
      initialDelaySeconds: 5
      periodSeconds: 5
